### ISSUE TITLE
Card shows blank name when friendly name is blank string

### ISSUE THREAD

**Issue by speedst3r** [ping-localhost/seventeen-track-card#4]
**Version of the cusom_component**
v1.0.2

**Describe the bug**
Some packages without friendly names from 17track have a blank string instead of null. These packages do not render names in the card, only tracking status. 
![17track_card](https://user-images.githubusercontent.com/2178183/90097830-7310b200-dd69-11ea-9e59-4ea88eb81748.png)

**log**
packages_in_transit sensor
```
attribution: Data provided by 17track.net
packages: 
- friendly_name: ''
  info_text: Received by Australia Post
  status: In Transit
  tracking_number: <redacted>
- friendly_name: ''
  info_text: Item processed at facility
  status: In Transit
  tracking_number: <redacted>
- friendly_name: ''
  info_text: Depart from facility to service provider.
  status: In Transit
  tracking_number: <redacted>
- friendly_name: ''
  info_text: Item processed at facility
  status: In Transit
  tracking_number: <redacted>
- friendly_name: null
  info_text: ITEM PROCESSED AT POST FACILITY
  status: In Transit
  tracking_number: <redacted>
- friendly_name: ''
  info_text: International arrival - awaiting clearance
  status: In Transit
  tracking_number: <redacted>

unit_of_measurement: packages
friendly_name: Seventeentrack Packages In Transit
icon: mdi:package
```
